[package]
name = "ipnet"
version = "0.18.2"
authors = ["Kris Price <kris@krisprice.nz>"]
description = "Provides types and methods for working with IPv4 and IPv6 network addresses."
license = "MIT"
repository = "https://github.com/krisprice/ipnet"

[dependencies]
