[package]
name = "ipnet"
version = "0.13.3"
authors = ["Kris Price <kris@krisprice.nz>"]
description = "IpNet, Ipv4Net, and Ipv6Net types. Heavily under construction."
license = "MIT"
repository = "https://github.com/krisprice/ipnet"

[dependencies]
