[package]
name = "ipnet"
version = "2.12.0"
authors = ["Kris Price <kris@krisprice.nz>", "0xk1f0"]
description = "Provides types and useful methods for working with IPv4 and IPv6 network addresses, commonly called IP prefixes. The new `IpNet`, `Ipv4Net`, and `Ipv6Net` types build on the existing `IpAddr`, `Ipv4Addr`, and `Ipv6Addr` types already provided in Rust's standard library and align to their design to stay consistent. The module also provides useful traits that extend `Ipv4Addr` and `Ipv6Addr` with methods for `Add`, `Sub`, `BitAnd`, and `BitOr` operations. The module only uses stable feature so it is guaranteed to compile using the stable toolchain."
license = "MIT"
repository = "https://github.com/0xk1f0/ipnet"
keywords = ["IP", "CIDR", "network", "prefix", "subnet"]
categories = ["network-programming"]
readme = "README.md"
documentation = "https://docs.rs/ipnet"
edition = "2021"

[dependencies]
